---
output:
  pdf_document:
    includes:
      before_body: title.sty
    toc: true
    toc_depth: 1
    latex_engine: xelatex
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exploratory Data Analysis
```{r load-data}
library(pander)

## Function for reading in files
read_sample <- function(file.name) {
  ## Extract the sample name for naming the column
  sample.name <- strsplit(file.name, ".", fixed = TRUE)
  colname <- paste(sample.name[[1]][1], "_", sample.name[[1]][2])
  ## Read the data, setting the 'Gene' as row.names (column 1)
  sample <- read.table(file.name, sep="\t", row.names=NULL, col.names=c("Gene", colname))
  #fill=TRUE, header=FALSE,
  ## Rename the count column
  # names(sample)[2] <- colname
  ## Return a subset containing the 'Gene' and sample name columns
  return(sample[c(1, 2)])
}

file.names <- list.files()

## Read the FIRST sample
dataset <- read_sample(file.names[1])

## Read the rest of the sample group
for (file.name in file.names[2:48]) {
  sample <- read_sample(file.name)
  dataset <- merge(dataset, sample, by = 1)
}

pander(head(dataset))
```

